package io.github.stonley890.dreamvisitor.functions;

import io.github.stonley890.dreamvisitor.Dreamvisitor;
import org.bukkit.configuration.file.FileConfiguration;

import java.time.Duration;

public class YearTracker {

    private static final FileConfiguration config = Dreamvisitor.getPlugin().getConfig();

    public static int getYear() {
        refresh();
        return config.getInt("currentYear");
    }

    public static Duration timeUntilNextYear() {
        refresh();
        long lastUpdateMilli = config.getLong("lastUpdateMilli");
        long intervalMilli = config.getLong("minutesPerYear") * 60 * 1000;
        return Duration.ofMillis((lastUpdateMilli + intervalMilli) - System.currentTimeMillis());
    }

    public static Duration timePerYear() {
        return Duration.ofMinutes(config.getLong("minutesPerYear"));
    }

    /**
     * Recalculate the current year.
     * Some of this code was generated by a LLM.
     */
    public static void refresh() {
        Dreamvisitor.debug("Refreshing year.");
        long currentYear = config.getLong("currentYear");
        Dreamvisitor.debug("Current year: " + currentYear);
        long minutesPerYear = config.getLong("minutesPerYear");
        long lastUpdateMilli = config.getLong("lastUpdateMilli");
        Dreamvisitor.debug("Last update milli: " + lastUpdateMilli);
        long currentTimeMilli = System.currentTimeMillis();
        Dreamvisitor.debug("Current system milli: " + currentTimeMilli);
        long elapsedTimeMilli = currentTimeMilli - lastUpdateMilli;
        Dreamvisitor.debug("Elapsed time milli: " + elapsedTimeMilli);

        long intervalMilli = minutesPerYear * 60 * 1000;
        Dreamvisitor.debug("interval milli: " + intervalMilli);
        long increments = elapsedTimeMilli / intervalMilli;
        Dreamvisitor.debug("increment count: " + increments);

        currentYear += (long) Math.floor(increments);
        Dreamvisitor.debug("New year: " + currentYear);
        lastUpdateMilli += increments * intervalMilli;
        Dreamvisitor.debug("New last update milli: " + lastUpdateMilli);

        config.set("currentYear", currentYear);
        config.set("lastUpdateMilli", lastUpdateMilli);
        Dreamvisitor.getPlugin().saveConfig();
    }

}
