main: io.github.stonley890.dreamvisitor.Dreamvisitor
name: Dreamvisitor
version: 2.8.3
api-version: 1.20
description: A plugin created by Bog for WoF:TNW to add various features.
author: Stonley890
softdepend:
  - EyeOfOnyx
  - Essentials
  - OpenRP

commands:
  dvset:
    description: Open Dreamvisitor settings.
    usage: /<command>
  pausechat:
    description: Pauses chat for non-OPs. Players will not be able to send messages, use `/me`, use OpenRP, or communicate through the game chat channel.
    usage: /<command> 
    permission: dreamvisitor.pausechat
  aradio:
    description: Sends a message to all OPs.
    usage: /<command> <message>
    permission: minecraft.command.op
  radio:
    description: Sends a message to all players with the dreamvisitor.radio permission.
    usage: /<command> <message>
    permission: dreamvisitor.radio
  tagradio:
    description: Sends a messages to all players with specified tag.
    usage: /<command> <tag> <message>
    permission: dreamvisitor.tagradio
  discord:
    description: Toggles Discord message visibility.
    usage: /<command>
  zoop:
    description: Vanish from Discord. Will send a 'Player left the game' message and remove you from Discord /list
    usage: /<command>
    permission: dreamvisitor.zoop
  softwhitelist:
    description: Add or remove a player to/from the soft whitelist. This acts as another whitelist 'layer' so that the main whitelist does not need to be modified.
    usage: /<command> <add|remove|list|on|off> [player]
    permission: dreamvisitor.softwhitelist
  playerlimit:
    description: Override server player limit.
    usage: /<command> <number of players (set -1 to disable)>
    permission: dreamvisitor.playerlimit
  togglepvp:
    description: Globally disable PvP.
    usage: /<command>
    permission: dreamvisitor.togglepvp
  pausebypass:
    description: Let certain players bypass chat pause.
    usage: /<command> <add|remove|list>
    permission: dreamvisitor.pausechat
  sethub:
    description: Set the hub location to teleport to with /hub. Must be run by a player.
    usage: /<command>
    permission: minecraft.command.op
  hub:
    description: Teleport to the hub location.
    usage: /<command>
  panic:
    description: Kicks all players and sets the player limit override to 0. You must run the command twice within 3 seconds to initiate the panic.
    usage: /<command>
    permission: dreamvisitor.panic
  itemblacklist:
    description: Access the item blacklist GUI. Items added to the blacklist will be removed from player inventories.
    usage: /<command>
    permission: dreamvisitor.itemblacklist
  user:
    description: Get the details of a player, even if they are offline.
    usage: /<command> <username>
    permission: dreamvisitor.user
  tribeupdate:
    description: Update roles based on in-game team.
    usage: /<command>
    permission: op
  unwax:
    description: Unwax the sign you are looking at.
    usage: /<command>
    permission: dreamvisitor.unwax
  schedulerestart:
    description: Schedule a server restart when no players are online.
    usage: /<command>
    permission: op
  invswap:
    description: Swap between two different inventories.
    usage: /<command>
    permission: dreamvisitor.invswap
  setmotd:
    description: Set the MOTD shown in the server list. Does not persist through restarts.
    usage: /<command> [MOTD]
    permission: dreamvisitor.setmotd

permissions:
  
  dreamvisitor.userset:
    description: Allow user settings configuration.
    default: true
  dreamvisitor.adminset:
    description: Allow admin settings configuration.
    default: op

  dreamvisitor.set.discord:
    description: Set Discord visibility for self.
    default: true
  dreamvisitor.set.zoop:
    description: Set Discord vanish for self.
    default: op
  dreamvisitor.set.autoinvswap:
    description: Set auto invswap for self.
    default: op
  dreamvisitor.set.autoradio:
    description: Set auto radio for self.
    default: op

  dreamvisitor.pausechat:
    description: Allows all chat pause commands.
    default: op
  dreamvisitor.nopause:
    description: Always allows bypassing chat pause.
    default: op
  dreamvisitor.tagradio:
    description: Allows the tagradio command.
    default: op
  dreamvisitor.zoop:
    description: Allows the zoop command.
    default: op
  dreamvisitor.softwhitelist:
    description: Allows the softwhitelist command.
    default: op
  dreamvisitor.nowhitelist:
    description: Always allows bypassing soft whitelist.
    default: op
  dreamvisitor.playerlimit:
    description: Allows the playerlimit command.
    default: op
  dreamvisitor.togglepvp:
    description: Allows the togglepvp command.
    default: op
  dreamvisitor.panic:
    description: Allows the panic command.
    default: op
  dreamvisitor.itemblacklist:
    description: Allows the itemblacklist command.
    default: op
  dreamvisitor.user:
    description: Allows the user command.
    default: op
  dreamvisitor.radio:
    description: Allows the radio command.
    default: op
  dreamvisitor.unwax:
    description:  Allows the unwax command.
    default: op
  dreamvisitor.invswap:
    description: Allows the invswap command.
    default: op
  dreamvisitor.hub:
    description: Allows the hub command.
    default: true
  dreamvisitor.hub.select:
    description: Allows using selectors with the hub command.
    default: op
  dreamvisitor.setmotd:
    description: Allows the setmotd command.
    default: op