main: io.github.stonley890.dreamvisitor.Dreamvisitor
name: Dreamvisitor
version: '${project.version}'
api-version: 1.20
description: A plugin created by Bog for WOFTNW to add various features.
author: Stonley890
softdepend:
  - EyeOfOnyx
  - Essentials
  - OpenRP
  - WorldGuard

permissions:
  
  dreamvisitor.userset:
    description: Allow user settings configuration.
    default: true

  dreamvisitor.set.discord:
    description: Set Discord visibility for self.
    default: true
  dreamvisitor.set.zoop:
    description: Set Discord vanish for self.
    default: op
  dreamvisitor.set.autoinvswap:
    description: Set auto invswap for self.
    default: op
  dreamvisitor.set.autoradio:
    description: Set auto radio for self.
    default: op

  dreamvisitor.pausechat:
    description: Allows all chat pause commands.
    default: op
  dreamvisitor.nopause:
    description: Always allows bypassing chat pause.
    default: op
  dreamvisitor.tagradio:
    description: Allows the tagradio command.
    default: op
  dreamvisitor.zoop:
    description: Allows the zoop command.
    default: op
  dreamvisitor.softwhitelist:
    description: Allows the softwhitelist command.
    default: op
  dreamvisitor.nowhitelist:
    description: Always allows bypassing soft whitelist.
    default: op
  dreamvisitor.playerlimit:
    description: Allows the playerlimit command.
    default: op
  dreamvisitor.togglepvp:
    description: Allows the togglepvp command.
    default: op
  dreamvisitor.panic:
    description: Allows the panic command.
    default: op
  dreamvisitor.itembanlist:
    description: Allows the itemblacklist command.
    default: op
  dreamvisitor.user:
    description: Allows the user command.
    default: op
  dreamvisitor.radio:
    description: Allows the radio command.
    default: op
  dreamvisitor.unwax:
    description:  Allows the unwax command.
    default: op
  dreamvisitor.invswap:
    description: Allows the invswap command.
    default: op
  dreamvisitor.hub:
    description: Allows the hub command.
    default: true
  dreamvisitor.hub.leash:
    description: Allows bringing entities on leashes to the hub.
    default: true
  dreamvisitor.hub.select:
    description: Allows using selectors with the hub command.
    default: op
  dreamvisitor.setmotd:
    description: Allows the setmotd command.
    default: op
  dreamvisitor.synctime:
    description: Allows the synctime command.
    default: op
  dreamvisitor.sandbox:
    description: Allows for sandbox management.
    default: op
  dreamvisitor.moonglobes:
    description: Allows using the moonglobes command.
    default: op
  dreamvisitor.tribeupdate:
    description: Allows using the tribeupdate command.
    default: op
  dreamvisitor.mail.play:
    description: Allows participation in the mail minigame.
    default: true
  dreamvisitor.mail.manage:
    description: Manage the mail minigame.
    default: op
  dreamvisitor.fly:
    description: Allows dragon flight
    default: true